<a href="https://colab.research.google.com/github/psukphranee/Python/blob/master/Calculate_Eulerian_Polynomial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Calculate Eulerian Polynomials

## 1. Implementation Code.

To run code, scroll to Section 2 for instruction on implementing.

In [17]:
import numpy as np
import itertools
import logging
import sys
import time
import os
from datetime import datetime


In [18]:
log_dir = '/content/eulerian_polynomials/logs'
os.makedirs(log_dir, exist_ok=True)  # Create the directory if it doesn't exist
# log_file = os.path.join(log_dir, f'descent_counts_log_{timestamp}.txt')

# # Configure logging
# logging.basicConfig(filename=log_file,
#                     filemode='a',
#                     format='',
#                     force=True,
#                     level=logging.INFO)

In [19]:
def print_sorted_dict(d):
    # Sort the dictionary by keys
    sorted_items = sorted(d.items())

    # Print each key-value pair
    for key, value in sorted_items:
        print(f'{key}: {value}')

In [20]:
#wrap the incidence matrix to make the appended incidence matrix
def append_incidence_matrix(incidence_matrix):

    numRows, numCols = incidence_matrix.shape

    # Add a row of zeros at the top
    appended = np.vstack([np.zeros((1, numCols)), incidence_matrix])

    # Create a new column with a 1 in the second position
    add_col = np.zeros((numRows + 1, 1))
    add_col[1] = 1

    # Add the new column to the left of the appended matrix
    appended = np.hstack([add_col, appended])

    return appended

In [21]:
# Function to calculate the descent counts
def calculate_descent_counts(Sigma, print_output=True, title=''):

    # Generate a timestamp string
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')

    # Create a unique log file name using the timestamp
    log_file = os.path.join(log_dir, f'descent_counts_log_{timestamp}.txt')

    logging.basicConfig(filename=log_file,
                        filemode='a',
                        format='',
                        force=True,
                        level=logging.INFO)

    if print_output:
      print(title)
    logging.info(title)

    # Generate vector of permutations
    n = Sigma.shape[0]  # Specify the value of n
    message = f'n = {n}'
    # if print_output:
    print(message)
    logging.info(message)

    # Append Sigma
    Sigma_appended = append_incidence_matrix(Sigma)
    message = f'Appended Incidence Matrix: \n{Sigma_appended}'
    if print_output:
      print(message)
    logging.info(message)

    # Vector of descent counts 0 to n
    descent_counts = dict()
    message = f'Vector of descent counts (0 to n): {descent_counts}'
    if print_output:
      print(message)
    #logging.info(message)

    # Vector of elements of [n] to be permuted
    elements = list(range(1, n + 1))

    # Generate all permutations and combinations of -1, +1
    perms = itertools.permutations(elements)

    # Iterate through the permutations
    message = 'Iterating through signed permutations...'
    # if print_output:
    print(message)
    logging.info(message)

    #setup counter to make sure we get 2^n * n! iterations
    counter = 0

    for perm in perms:
        # Convert the tuple into a np array
        perm_vect = np.array(perm)

        comb = itertools.product([-1, 1], repeat=n)
        # Iterate through the combinations
        for c in comb:
            # Convert the tuple into a np array
            epsilon_vect = np.array(c)

            # Create signed permutation and insert 0 at the beginning of the vector
            pi_epsilon = np.multiply(perm_vect, epsilon_vect)
            pi_epsilon = np.insert(pi_epsilon, 0, 0)

            # Multiply matrices
            prod = np.matmul(pi_epsilon, Sigma_appended)

            # Get descend number for this permutation
            numDesc = np.sum(prod < 0)

            # Increment the corresponding entry of the matrix
            descent_counts[numDesc] = descent_counts.get(numDesc, 0) + 1

            #increment counter
            counter += 1

            message = (f'counter:\n{counter}\npi_eps:\n{pi_epsilon}\nAppended Incidence Matrix:\n{Sigma_appended}\n'
                       f'Prod:\n{prod}\n#Des: {numDesc}')
            if print_output:
                print(message)
            logging.info(message)
            if print_output:
                print('------------------------------------------')
            logging.info('------------------------------------------')

    message = f'...completed {counter} iterations through signed permutations.'
    # if print_output:
    print(message)
    logging.info(message)


    return descent_counts

## 2. Implementing Code

The following cell is a template for executing the program.
1. Specify the incidence matrix (not appended incidence matrix)
2. Pass it to calculate_descent_counts(). This returns a dictionary
3. Use print_sorted_dict() to print the dictionary sorted by keys

A log will be output in "/content/eulerian_polynomials/logs" that shows the result of running through all signed permutations.

In [53]:
# Specify Indicence Matrix
Sigma = np.array([[0],[0]])
print('Sigma: \n', Sigma)

#optional title that appears at the top of the log file
title = f'Incidence matric corresponding to graph in example 1a'

descent_counts = calculate_descent_counts(Sigma, print_output=False, title=message)

print('Descent Counts: \n')
print_sorted_dict(descent_counts)

Sigma: 
 [[0]
 [0]]
n = 2
Iterating through signed permutations...
...completed 8 iterations through signed permutations.
Descent Counts: 

0: 4
1: 4


In [38]:
Sigma = np.array([[-1],[-1]])
print('Sigma: \n', Sigma)

message = f'Incidence matric corresponding to graph in example 1b'
descent_counts = calculate_descent_counts(Sigma, print_output=False, title=message)
print('Descent Counts: \n')
print_sorted_dict(descent_counts)

Sigma: 
 [[-1]
 [-1]]
n = 2
Iterating through signed permutations...
...completed 8 iterations through signed permutations.
Descent Counts: 

0: 1
1: 6
2: 1


In [39]:
Sigma = np.array([[0,0],[0,0],[0,0]])
print('Sigma: \n', Sigma)

message = f'Incidence matric corresponding to graph in 2a'
descent_counts = calculate_descent_counts(Sigma, print_output=False, title=message)
print('Descent Counts: \n')
print_sorted_dict(descent_counts)

Sigma: 
 [[0 0]
 [0 0]
 [0 0]]
n = 3
Iterating through signed permutations...
...completed 48 iterations through signed permutations.
Descent Counts: 

0: 24
1: 24


In [40]:
Sigma = np.array([[-1,0],[-1,0],[0,0]])
print('Sigma: \n', Sigma)

message = f'Incidence matric corresponding to graph in 2b'
descent_counts = calculate_descent_counts(Sigma, print_output=False, title=message)
print('Descent Counts: \n')
print_sorted_dict(descent_counts)

Sigma: 
 [[-1  0]
 [-1  0]
 [ 0  0]]
n = 3
Iterating through signed permutations...
...completed 48 iterations through signed permutations.
Descent Counts: 

0: 6
1: 36
2: 6


In [41]:
Sigma = np.array([[-1,0],[-1,-1],[0,-1]])
print('Sigma: \n', Sigma)

message = f'Incidence matric corresponding to graph in 2c'
descent_counts = calculate_descent_counts(Sigma, print_output=False, title=message)
print('Descent Counts: \n')
print_sorted_dict(descent_counts)

Sigma: 
 [[-1  0]
 [-1 -1]
 [ 0 -1]]
n = 3
Iterating through signed permutations...
...completed 48 iterations through signed permutations.
Descent Counts: 

0: 5
1: 19
2: 19
3: 5


In [42]:
Sigma = np.array([[0,0,0],[0,0,0],[0,0,0],[0,0,0]])
print('Sigma: \n', Sigma)

message = f'Incidence matric corresponding to graph in 3a'
descent_counts = calculate_descent_counts(Sigma, print_output=False, title=message)
print('Descent Counts: \n')
print_sorted_dict(descent_counts)

Sigma: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
n = 4
Iterating through signed permutations...
...completed 384 iterations through signed permutations.
Descent Counts: 

0: 192
1: 192


In [43]:
Sigma = np.array([[-1,0,0],[0,0,0],[0,0,0],[-1,0,0]])
print('Sigma: \n', Sigma)

message = f'Incidence matric corresponding to graph in 3b'
descent_counts = calculate_descent_counts(Sigma, print_output=False, title=message)
print('Descent Counts: \n')
print_sorted_dict(descent_counts)

Sigma: 
 [[-1  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [-1  0  0]]
n = 4
Iterating through signed permutations...
...completed 384 iterations through signed permutations.
Descent Counts: 

0: 48
1: 288
2: 48


In [44]:
Sigma = np.array([[-1,0,0],[0,0,0],[-1,-1,0],[0,-1,0]])
print('Sigma: \n', Sigma)

message = f'Incidence matric corresponding to graph in 3c'
descent_counts = calculate_descent_counts(Sigma, print_output=False, title=message)
print('Descent Counts: \n')
print_sorted_dict(descent_counts)

Sigma: 
 [[-1  0  0]
 [ 0  0  0]
 [-1 -1  0]
 [ 0 -1  0]]
n = 4
Iterating through signed permutations...
...completed 384 iterations through signed permutations.
Descent Counts: 

0: 40
1: 152
2: 152
3: 40


In [45]:
Sigma = np.array([[-1,0,0],[-1,-1,0],[0,-1,-1],[0,0,-1]])
print('Sigma: \n', Sigma)

message = f'Incidence matric corresponding to graph in 3d'
descent_counts = calculate_descent_counts(Sigma, print_output=False, title=message)
print('Descent Counts: \n')
print_sorted_dict(descent_counts)

Sigma: 
 [[-1  0  0]
 [-1 -1  0]
 [ 0 -1 -1]
 [ 0  0 -1]]
n = 4
Iterating through signed permutations...
...completed 384 iterations through signed permutations.
Descent Counts: 

0: 23
1: 116
2: 106
3: 116
4: 23


In [46]:
Sigma = np.array([[0],[0],[0],[0]])
print('Sigma: \n', Sigma)

message = f'Incidence matric corresponding to graph in 4a'
descent_counts = calculate_descent_counts(Sigma, print_output=False, title=message)
print('Descent Counts: \n')
print_sorted_dict(descent_counts)

Sigma: 
 [[0]
 [0]
 [0]
 [0]]
n = 4
Iterating through signed permutations...
...completed 384 iterations through signed permutations.
Descent Counts: 

0: 192
1: 192


In [47]:
Sigma = np.array([[-1],[-1],[0],[0]])
print('Sigma: \n', Sigma)

message = f'Incidence matric corresponding to graph in 4b'
descent_counts = calculate_descent_counts(Sigma, print_output=False, title=message)
print('Descent Counts: \n')
print_sorted_dict(descent_counts)

Sigma: 
 [[-1]
 [-1]
 [ 0]
 [ 0]]
n = 4
Iterating through signed permutations...
...completed 384 iterations through signed permutations.
Descent Counts: 

0: 48
1: 288
2: 48


In [49]:
Sigma = np.array([[-1,-1],[-1,0],[0,-1],[0,0]])
print('Sigma: \n', Sigma)

message = f'Incidence matric corresponding to graph in 4c'
descent_counts = calculate_descent_counts(Sigma, print_output=False, title=message)
print('Descent Counts: \n')
print_sorted_dict(descent_counts)

Sigma: 
 [[-1 -1]
 [-1  0]
 [ 0 -1]
 [ 0  0]]
n = 4
Iterating through signed permutations...
...completed 384 iterations through signed permutations.
Descent Counts: 

0: 16
1: 176
2: 176
3: 16


In [50]:
Sigma = np.array([[-1,-1,0],[-1,0,-1],[0,-1,-1],[0,0,0]])
print('Sigma: \n', Sigma)

message = f'Incidence matric corresponding to graph in 4d'
descent_counts = calculate_descent_counts(Sigma, print_output=False, title=message)
print('Descent Counts: \n')
print_sorted_dict(descent_counts)

Sigma: 
 [[-1 -1  0]
 [-1  0 -1]
 [ 0 -1 -1]
 [ 0  0  0]]
n = 4
Iterating through signed permutations...
...completed 384 iterations through signed permutations.
Descent Counts: 

0: 16
1: 128
2: 96
3: 128
4: 16


In [51]:
Sigma = np.array([[-1,-1,0,0],[1,0,1,1],[0,0,-1,0],[0,-1,0,1]])
print('Sigma: \n', Sigma)

message = f'Incidence matric corresponding to graph in 5a'
descent_counts = calculate_descent_counts(Sigma, print_output=False, title=message)
print('Descent Counts: \n')
print_sorted_dict(descent_counts)

Sigma: 
 [[-1 -1  0  0]
 [ 1  0  1  1]
 [ 0  0 -1  0]
 [ 0 -1  0  1]]
n = 4
Iterating through signed permutations...
...completed 384 iterations through signed permutations.
Descent Counts: 

0: 7
1: 75
2: 110
3: 110
4: 75
5: 7


In [52]:
Sigma = np.array([[-1,-1,0,0,-1],[1,0,1,1,0],[0,0,-1,0,-1],[0,-1,0,1,0]])
print('Sigma: \n', Sigma)

message = f'Incidence matric corresponding to graph in 5b'
descent_counts = calculate_descent_counts(Sigma, print_output=False, title=message)
print('Descent Counts: \n')
print_sorted_dict(descent_counts)

Sigma: 
 [[-1 -1  0  0 -1]
 [ 1  0  1  1  0]
 [ 0  0 -1  0 -1]
 [ 0 -1  0  1  0]]
n = 4
Iterating through signed permutations...
...completed 384 iterations through signed permutations.
Descent Counts: 

0: 3
1: 54
2: 93
3: 84
4: 93
5: 54
6: 3
